config/routes.rb
require 'api/api'

Gitlab::Application.routes.draw do
  get 'build' => 'build#index'
  get 'build/show/:id' => 'build#show', constraints: {id: /\d+/}
  get 'build/delete/:id' => 'build#delete', constraints: {id: /\d+/}
  post 'projects/run' => "projects#run"

  # user leads
  post 'user_lead/create'

  #
  # Search
  #
  get 'search' => "search#show"
  get 'search/autocomplete' => "search#autocomplete", as: :search_autocomplete

  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  # Get all keys of user
  get ':username.keys' => 'profiles/keys#get_keys' , constraints: { username: /.*/ }

  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }

  # Enable Grack support
  mount Grack::Bundle.new({
    git_path:     Gitlab.config.git.bin_path,
    project_root: Gitlab.config.gitlab_shell.repos_path,
    upload_pack:  Gitlab.config.gitlab_shell.upload_pack,
    receive_pack: Gitlab.config.gitlab_shell.receive_pack
  }), at: '/', constraints: lambda { |request| /[-\/\w\.]+\.git\//.match(request.path_info) }, via: [:get, :post]

  #
  # Help
  #
  get 'help'                => 'help#index'
  get 'help/api'            => 'help#api'
  get 'help/api/:category'  => 'help#api', as: 'help_api_file'
  get 'help/markdown'       => 'help#markdown'
  get 'help/permissions'    => 'help#permissions'
  get 'help/public_access'  => 'help#public_access'
  get 'help/raketasks'      => 'help#raketasks'
  get 'help/ssh'            => 'help#ssh'
  get 'help/system_hooks'   => 'help#system_hooks'
  get 'help/web_hooks'      => 'help#web_hooks'
  get 'help/workflow'       => 'help#workflow'
  get 'help/shortcuts'
  get 'help/security'

  #
  # Global snippets
  #
  resources :snippets do
    member do
      get "raw"
    end
  end
  get "/s/:username" => "snippets#user_index", as: :user_snippets, constraints: { username: /.*/ }

  #
  # Public namespace
  #
  namespace :public do
    resources :projects, only: [:index]
    root to: "projects#index"
  end

  #
  # Attachments serving
  #
  get 'files/:type/:id/:filename' => 'files#download', constraints: { id: /\d+/, type: /[a-z]+/, filename:  /.+/ }

  #
  # Admin Area
  #
  namespace :admin do
    resources :users, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ } do
      member do
        put :team_update
        put :block
        put :unblock
      end
    end

    resources :groups, constraints: { id: /[^\/]+/ } do
      member do
        put :project_teams_update
      end
    end

    resources :hooks, only: [:index, :create, :destroy] do
      get :test
    end

    resources :broadcast_messages, only: [:index, :create, :destroy]
    resource :logs, only: [:show]
    resource :background_jobs, controller: 'background_jobs', only: [:show]

    resources :projects, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }, only: [:index, :show] do
      member do
        put :transfer
      end
    end

    root to: "dashboard#index"
  end

  #
  # Profile Area
  #
  resource :profile, only: [:show, :update] do
    member do
      get :history
      get :design

      put :reset_private_token
      put :update_username
    end

    scope module: :profiles do
      resource :account, only: [:show, :update]
      resource :notifications, only: [:show, :update]
      resource :password, only: [:new, :create, :edit, :update] do
        member do
          put :reset
        end
      end
      resources :keys
      resources :emails, only: [:index, :create, :destroy]
      resources :groups, only: [:index] do
        member do
          delete :leave
        end
      end
      resource :avatar, only: [:destroy]
    end
  end

  match "/u/:username" => "users#show", as: :user, constraints: { username: /.*/ }, via: :get



  #
  # Dashboard Area
  #
  resource :dashboard, controller: "dashboard", only: [:show] do
    member do
      get :projects
      get :issues
      get :merge_requests
    end
  end

  #
  # Groups Area
  #
  resources :groups, constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/}  do
    member do
      get :issues
      get :merge_requests
      get :members
    end

    resources :users_groups, only: [:create, :update, :destroy]
    scope module: :groups do
      resource :avatar, only: [:destroy]
    end
  end

  resources :projects, constraints: { id: /[^\/]+/ }, only: [:new, :create]

  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks, registrations: :registrations }

  #
  # Project Area
  #
  resources :projects, constraints: { id: /[a-zA-Z.0-9_\-]+\/[a-zA-Z.0-9_\-]+/ }, except: [:new, :create, :index], path: "/" do
    member do
      put :transfer
      post :fork
      get :ci_build
      post "ci_build_single/:sha/:test_id" => "projects#ci_build_single", constraints: {sha: /\w+/, test_id: /.+/}, as: 'ci_build_single'
      get :ci
      put :ci_update
      post :unarchive
      get :autocomplete_sources
      get :runner_configs
    end

    scope module: :projects do
      resources :summary,   only: [:index], constraints: {id: /.+/}
      resources :test_issues,   only: [:index]
      resources :results,   only: [:index]
      resources :blob,      only: [:show, :destroy], constraints: {id: /.+/}
      resources :raw,       only: [:show], constraints: {id: /.+/}
      resources :tree,      only: [:show], constraints: {id: /.+/, format: /(html|js)/ }
      resources :edit_tree, only: [:show, :update], constraints: {id: /.+/}, path: 'edit'
      resources :new_tree,  only: [:show, :update], constraints: {id: /.+/}, path: 'new'
      resources :commit,    only: [:show], constraints: {id: /[[:alnum:]]{6,40}/}
      resources :commits,   only: [:show], constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/}
      resources :blame,     only: [:show], constraints: {id: /.+/}

      match "/compare/:from...:to" => "compare#show", as: "compare", via: [:get, :post], constraints: {from: /.+/, to: /.+/}

        resources :snippets, constraints: {id: /\d+/} do
          member do
            get "raw"
          end
        end

      resources :wikis, only: [:show, :edit, :destroy, :create], constraints: {id: /[a-zA-Z.0-9_\-]+/} do
        collection do
          get :pages
          put ':id' => 'wikis#update'
          get :git_access
        end

        member do
          get "history"
        end
      end

      resource :wall, only: [:show], constraints: {id: /\d+/} do
        member do
          get 'notes'
        end
      end

      resource :repository, only: [:show] do
        member do
          get "stats"
          get "archive", constraints: { format: Gitlab::Regex.archive_formats_regex }
        end
      end

      resources :services, constraints: { id: /[^\/]+/ }, only: [:index, :edit, :update] do
        member do
          get :test
        end
      end

      resources :deploy_keys, constraints: {id: /\d+/} do
        member do
          put :enable
          put :disable
        end
      end

      resources :branches, only: [:index, :new, :create, :destroy], constraints: { id: Gitlab::Regex.git_reference_regex } do
        collection do
          get :recent, constraints: { id: Gitlab::Regex.git_reference_regex }
        end
      end

      resources :tags, only: [:index, :new, :create, :destroy], constraints: { id: Gitlab::Regex.git_reference_regex }
      resources :protected_branches, only: [:index, :create, :destroy], constraints: { id: Gitlab::Regex.git_reference_regex }

      resources :refs, only: [] do
        collection do
          get "switch"
        end

        member do
          # tree viewer logs
          get "logs_tree", constraints: { id: Gitlab::Regex.git_reference_regex }
          get "logs_tree/:path" => "refs#logs_tree",
            as: :logs_file,
            constraints: {
              id:   Gitlab::Regex.git_reference_regex,
              path: /.*/
            }
        end
      end

      resources :merge_requests, constraints: {id: /\d+/}, except: [:destroy] do
        member do
          get :diffs
          get :automerge
          get :automerge_check
          get :ci_status
        end

        collection do
          get :branch_from
          get :branch_to
          get :update_branches
        end
      end

      resources :hooks, only: [:index, :create, :destroy], constraints: {id: /\d+/} do
        member do
          get :test
        end
      end

      resources :team, controller: 'team_members', only: [:index]
      resources :milestones, except: [:destroy], constraints: {id: /\d+/}

      resources :labels, only: [:index] do
        collection do
          post :generate
        end
      end

      resources :issues, constraints: {id: /\d+/}, except: [:destroy] do
        collection do
          post  :bulk_update
        end
      end

      resources :team_members, except: [:index, :edit], constraints: { id: /[a-zA-Z.\/0-9_\-#%+]+/ } do
        collection do
          delete :leave

          # Used for import team
          # from another project
          get :import
          post :apply_import
        end
      end

      resources :notes, only: [:index, :create, :destroy, :update], constraints: {id: /\d+/} do
        member do
          delete :delete_attachment
        end

        collection do
          post :preview
        end
      end
    end
  end

  root to: "dashboard#show"
end

app/controllers/projects/application_controller.rb
class Projects::ApplicationController < ApplicationController
  before_filter :project
  before_filter :repository
  layout :determine_layout

  def authenticate_user!
    # Restrict access to Projects area only
    # for non-signed users
    if !current_user
      id = params[:project_id] || params[:id]
      @project = Project.find_with_namespace(id)

      return if @project && @project.public?
    end

    super
  end

  def determine_layout
    if current_user
      'projects'
    else
      'public_projects'
    end
  end

  def require_branch_head
    unless @repository.branch_names.include?(@ref)
      redirect_to project_tree_path(@project, @ref), notice: "This action is not allowed unless you are on top of a branch"
    end
  end

  def paginate(page_num, expanded, blocks)

    if(page_num.nil?)
      page_num = 1
    else
      page_num = page_num.to_d
    end

    sorted_blocks_unsliced =blocks.sort_by { |i| yield(i).feature }

    if(!(expanded.nil? || expanded.empty?))
      expanded_id = expanded.first

      index = sorted_blocks_unsliced.index { |i| i.id.to_s == expanded_id }

      if(!index.nil?)
        block_page_num = index.fdiv(PER_PAGE).truncate + 1

        if(block_page_num != page_num)
          return {:redirect => true, :addons => {:page => block_page_num}}
        end
      end
    end

    total_results = blocks.length

    offset = (page_num-1)*PER_PAGE
    limit = [ offset+PER_PAGE, total_results+1 ].min
    num_pages = total_results.fdiv(PER_PAGE).ceil
    num_pages = num_pages == 0 ? 1 : num_pages

    blocks_by_feature = {}

    sorted_blocks = sorted_blocks_unsliced[offset..limit-1]

    sorted_blocks.each { |i|
      feature = yield(i).feature

      if(blocks_by_feature[feature].nil?)
        blocks_by_feature[feature] = [i]
      else
        blocks_by_feature[feature] << i
      end
    }

    {:redirect => false, :num_pages => num_pages, :page_num => page_num, :blocks_by_feature => blocks_by_feature}
  end
end

app/controllers/projects/base_tree_controller.rb
class Projects::BaseTreeController < Projects::ApplicationController
  include ExtractsPath


  # before_filter :require_non_empty_project
end

app/controllers/projects/blame_controller.rb
# Controller for viewing a file's blame
class Projects::BlameController < Projects::ApplicationController
  include ExtractsPath

  # Authorize
  before_filter :require_non_empty_project

  def show
    @blob = @repository.blob_at(@commit.id, @path)
    @blame = Gitlab::Git::Blame.new(project.repository, @commit.id, @path)
  end
end

app/controllers/projects/commits_controller.rb
require "base64"

class Projects::CommitsController < Projects::ApplicationController
  include ExtractsPath

  # Authorize
  before_filter :require_non_empty_project

  def show
    @repo = @project.repository
    @limit, @offset = (params[:limit] || 40), (params[:offset] || 0)

    @commits = @repo.commits(@ref, @path, @limit, @offset)

    respond_to do |format|
      format.html # index.html.erb
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def remove_from_project_team_message(project, user)
    "You are going to remove #{user.name} from #{project.name} project team. Are you sure?"
  end

  def link_to_project project
    link_to project do
      title = content_tag(:span, project.name, class: 'projet-name')

      if project.namespace
        namespace = content_tag(:span, "#{project.namespace.human_name} / ", class: 'namespace-name')
        title = namespace + title
      end

      title
    end
  end

  def link_to_member(project, author, opts = {})
    default_opts = { avatar: true, name: true, size: 16 }
    opts = default_opts.merge(opts)

    return "(deleted)" unless author

    author_html =  ""

    # Build avatar image tag
    author_html << image_tag(avatar_icon(author.try(:email), opts[:size]), width: opts[:size], class: "avatar avatar-inline #{"s#{opts[:size]}" if opts[:size]}", alt:'') if opts[:avatar]

    # Build name span tag
    author_html << content_tag(:span, sanitize(author.name), class: 'author') if opts[:name]

    author_html = author_html.html_safe

    if opts[:name]
      link_to(author_html, user_path(author), class: "author_link").html_safe
    else
      link_to(author_html, user_path(author), class: "author_link has_tooltip", data: { :'original-title' => sanitize(author.name) } ).html_safe
    end
  end

  def project_title project
    if project.group
      content_tag :span do
        project.name
        # link_to(simple_sanitize(project.group.name), group_path(project.group)) + " / " + project.name
      end
    else
      owner = project.namespace.owner
      content_tag :span do
        project.name
        # link_to(simple_sanitize(owner.name), profile_path(owner)) + " / " + project.name
      end
    end
  end

  def project_link_to_user
    link_to(simple_sanitize(current_user.name), profile_path)
  end

  def remove_project_message(project)
    "You are going to remove #{project.name_with_namespace}.\n Removed project CANNOT be restored!\n Are you ABSOLUTELY sure?"
  end

  def project_nav_tabs
    @nav_tabs ||= get_project_nav_tabs(@project, current_user)
  end

  def project_nav_tab?(name)
    project_nav_tabs.include? name
  end

  def selected_label?(label_name)
    params[:label_name].to_s.split(',').include?(label_name)
  end

  def labels_filter_path(label_name)
    label_name =
      if selected_label?(label_name)
        params[:label_name].split(',').reject { |l| l == label_name }.join(',')
      elsif params[:label_name].present?
        "#{params[:label_name]},#{label_name}"
      else
        label_name
      end

    project_filter_path(label_name: label_name)
  end

  def label_filter_class(label_name)
    if selected_label?(label_name)
      'label-filter-item active'
    else
      'label-filter-item light'
    end
  end

  def project_filter_path(options={})
    exist_opts = {
      state: params[:state],
      scope: params[:scope],
      label_name: params[:label_name],
      milestone_id: params[:milestone_id],
      assignee_id: params[:assignee_id],
      sort: params[:sort],
    }

    options = exist_opts.merge(options)

    path = request.path
    path << "?#{options.to_param}"
    path
  end

  
  private

  def get_project_nav_tabs(project, current_user)
    nav_tabs = [:home]

    if !project.empty_repo? && can?(current_user, :download_code, project)
      nav_tabs << [:files, :commits, :network, :graphs]
    end

    if can?(current_user, :admin_project, project)
      nav_tabs << :settings
    end

    nav_tabs.flatten
  end

  def git_user_name
    if current_user
      current_user.name
    else
      "Your name"
    end
  end

  def git_user_email
    if current_user
      current_user.email
    else
      "your@email.com"
    end
  end

  def repository_size(project = nil)
    "#{(project || @project).repository.size} MB"
  rescue
    # In order to prevent 500 error
    # when application cannot allocate memory
    # to calculate repo size - just show 'Unknown'
    'unknown'
  end

  def project_head_title
    title = @project.name
    # title = @project.name_with_namespace

    title = if current_controller?(:tree)
              "#{@project.path}\/#{@path} at #{@ref} - " + title
            elsif current_controller?(:blob)
              "#{@project.path}\/#{@blob.path} at #{@ref} - " + title
            elsif current_controller?(:commits)
              "Commits at #{@ref} - " + title
            else
              title
            end

    title
  end

  def default_url_to_repo(project = nil)
    project = project || @project
    current_user ? project.url_to_repo : project.http_url_to_repo
  end

  def default_clone_protocol
    current_user ? "ssh" : "http"
  end

  def project_last_activity(project)
    if project.last_activity_at
      time_ago_with_tooltip(project.last_activity_at, 'bottom', 'last_activity_time_ago')
    else
      "Never"
    end
  end
end

app/views/projects/blob/_actions.html.haml
.btn-group.tree-btn-group
  -# only show edit link for text files
  - if @blob.text?
    - if allowed_tree_edit? && @is_editable
      = link_to "edit", project_edit_tree_path(@project, @id), class: "btn btn-small"
    - else
      %span.btn.btn-small.disabled edit
  = link_to "raw", project_raw_path(@project, @id), class: "btn btn-small", target: "_blank"
  -# only show normal/blame view links for text files
  - if @blob.text?
    - if current_page? project_blame_path(@project, @id)
      = link_to "normal view", project_blob_path(@project, @id), class: "btn btn-small"
    - else
      = link_to "blame", project_blame_path(@project, @id), class: "btn btn-small" unless @blob.empty?

  - if allowed_tree_edit?
    = link_to '#modal-remove-blob', class: "remove-blob btn btn-small btn-remove", "data-toggle" => "modal" do
      remove

= render 'projects/blob/remove'

= javascript_include_tag "bootstrap"

app/views/projects/blob/_blob.html.haml
-if(!@is_editable)
  %div.alert.alert-warning
    This file cannot be edited because you may be seeing an old version.
    =link_to 'Click here', project_blob_path(:class => "alert-link", :id => @project.repository.root_ref + '/' + @path)
    to try to go to the current version.
%div#tree-content-holder.tree-content-holder
  .file-holder
    .file-title
      %i.icon-file
      %span.file_name
        = blob.name
        %small= number_to_human_size blob.size
      %span.options= render "actions"
    - if blob.text?
      = render "text", blob: blob
    - elsif blob.image?
      = render "image", blob: blob
    - else
      = render "download", blob: blob

app/views/projects/blob/_download.html.haml
.file-content.blob_file.blob-no-preview
  %center
    = link_to project_raw_path(@project, @id) do
      %h1.light
        %i.icon-download-alt
      %h4
        Download (#{number_to_human_size blob.size})

app/views/projects/blob/_image.html.haml
.file-content.image_file
  %img{ src: "data:#{blob.mime_type};base64,#{Base64.encode64(blob.data)}"}

app/views/projects/blob/_remove.html.haml
#modal-remove-blob.modal.hide
  .modal-dialog
    .modal-content
      .modal-header
        %a.close{href: "#", "data-dismiss" => "modal"} ×
        %h3.page-title Remove #{@blob.name}
        %p.light
          From branch
          %strong= @ref

      .modal-body
        = form_tag project_blob_path(@project, @id), method: :delete, class: 'form-horizontal' do
          .form-group.commit_message-group
            = label_tag 'commit_message', class: "control-label" do
              Commit message
            .col-sm-10
              = text_area_tag 'commit_message', params[:commit_message], placeholder: "Removed this file because...", required: true, rows: 3, class: 'form-control'
          .form-group
            .col-sm-2
            .col-sm-10
              = submit_tag 'Remove file', class: 'btn btn-remove'
              = link_to "Cancel", '#', class: "btn btn-cancel", "data-dismiss" => "modal"

app/views/projects/blob/_text.html.haml
- if gitlab_markdown?(blob.name)
  .file-content.wiki
    = preserve do
      -#= markdown(blob.data)
      = render 'shared/file_hljs', blob: blob
- elsif markup?(blob.name)
  .file-content.wiki
    = render_markup(blob.name, blob.data)
- else
  .file-content.code
    - unless blob.empty?
      = render 'shared/file_hljs', blob: blob
    - else
      .nothing-here-block Empty file

app/views/projects/blob/show.html.haml
= javascript_include_tag "lib/jquery.timeago"

%div.tree-ref-holder
  = render 'shared/ref_switcher', destination: 'blob', path: @path
  %ul.breadcrumb
    %li
      %i.icon-angle-right
      = link_to project_tree_path(@project, @ref) do
        = @project.path
    - tree_breadcrumbs(@tree, 6) do |title, path|
      %li
        - if path
          - if path.end_with?(@path)
            = link_to project_blob_path(@project, path) do
              %span.cblue
                = truncate(title, length: 40)
          - else
            = link_to truncate(title, length: 40), project_tree_path(@project, path)
        - else
          = link_to title, '#'

%ul.blob-commit-info.bs-callout.bs-callout-info
  - blob_commit = @repository.last_commit_for_path(@commit.id, @blob.path)
  = render blob_commit, project: @project

%div#tree-holder.tree-holder
  = render 'blob', blob: @blob

%div.run-single-holder
  -if @blob.is_feature?
    .form-holder
      = form_for @project, url: ci_build_single_project_path(@project, @commit.id, @blob.path), method: :post do |f|
        = f.submit "Run now", class: "btn btn-primary", disabled: !@project.has_ci_settings?

= javascript_include_tag "select2"
:javascript
  $('select.select2').select2({width: 'resolve', dropdownAutoWidth: true});
  $('.project-refs-select').on('change', function() {
    $(this).parents('form').submit();
  });