config/routes.rb
require 'api/api'

Gitlab::Application.routes.draw do
  get 'build' => 'build#index'
  get 'build/show/:id' => 'build#show', constraints: {id: /\d+/}
  get 'build/delete/:id' => 'build#delete', constraints: {id: /\d+/}
  post 'projects/run' => "projects#run"

  # user leads
  post 'user_lead/create'

  #
  # Search
  #
  get 'search' => "search#show"
  get 'search/autocomplete' => "search#autocomplete", as: :search_autocomplete

  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  # Get all keys of user
  get ':username.keys' => 'profiles/keys#get_keys' , constraints: { username: /.*/ }

  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }

  # Enable Grack support
  mount Grack::Bundle.new({
    git_path:     Gitlab.config.git.bin_path,
    project_root: Gitlab.config.gitlab_shell.repos_path,
    upload_pack:  Gitlab.config.gitlab_shell.upload_pack,
    receive_pack: Gitlab.config.gitlab_shell.receive_pack
  }), at: '/', constraints: lambda { |request| /[-\/\w\.]+\.git\//.match(request.path_info) }, via: [:get, :post]

  #
  # Help
  #
  get 'help'                => 'help#index'
  get 'help/api'            => 'help#api'
  get 'help/api/:category'  => 'help#api', as: 'help_api_file'
  get 'help/markdown'       => 'help#markdown'
  get 'help/permissions'    => 'help#permissions'
  get 'help/public_access'  => 'help#public_access'
  get 'help/raketasks'      => 'help#raketasks'
  get 'help/ssh'            => 'help#ssh'
  get 'help/system_hooks'   => 'help#system_hooks'
  get 'help/web_hooks'      => 'help#web_hooks'
  get 'help/workflow'       => 'help#workflow'
  get 'help/shortcuts'
  get 'help/security'

  #
  # Global snippets
  #
  resources :snippets do
    member do
      get "raw"
    end
  end
  get "/s/:username" => "snippets#user_index", as: :user_snippets, constraints: { username: /.*/ }

  #
  # Public namespace
  #
  namespace :public do
    resources :projects, only: [:index]
    root to: "projects#index"
  end

  #
  # Attachments serving
  #
  get 'files/:type/:id/:filename' => 'files#download', constraints: { id: /\d+/, type: /[a-z]+/, filename:  /.+/ }

  #
  # Admin Area
  #
  namespace :admin do
    resources :users, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ } do
      member do
        put :team_update
        put :block
        put :unblock
      end
    end

    resources :groups, constraints: { id: /[^\/]+/ } do
      member do
        put :project_teams_update
      end
    end

    resources :hooks, only: [:index, :create, :destroy] do
      get :test
    end

    resources :broadcast_messages, only: [:index, :create, :destroy]
    resource :logs, only: [:show]
    resource :background_jobs, controller: 'background_jobs', only: [:show]

    resources :projects, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }, only: [:index, :show] do
      member do
        put :transfer
      end
    end

    root to: "dashboard#index"
  end

  #
  # Profile Area
  #
  resource :profile, only: [:show, :update] do
    member do
      get :history
      get :design

      put :reset_private_token
      put :update_username
    end

    scope module: :profiles do
      resource :account, only: [:show, :update]
      resource :notifications, only: [:show, :update]
      resource :password, only: [:new, :create, :edit, :update] do
        member do
          put :reset
        end
      end
      resources :keys
      resources :emails, only: [:index, :create, :destroy]
      resources :groups, only: [:index] do
        member do
          delete :leave
        end
      end
      resource :avatar, only: [:destroy]
    end
  end

  match "/u/:username" => "users#show", as: :user, constraints: { username: /.*/ }, via: :get



  #
  # Dashboard Area
  #
  resource :dashboard, controller: "dashboard", only: [:show] do
    member do
      get :projects
      get :issues
      get :merge_requests
    end
  end

  #
  # Groups Area
  #
  resources :groups, constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/}  do
    member do
      get :issues
      get :merge_requests
      get :members
    end

    resources :users_groups, only: [:create, :update, :destroy]
    scope module: :groups do
      resource :avatar, only: [:destroy]
    end
  end

  resources :projects, constraints: { id: /[^\/]+/ }, only: [:new, :create]

  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks, registrations: :registrations }

  #
  # Project Area
  #
  resources :projects, constraints: { id: /[a-zA-Z.0-9_\-]+\/[a-zA-Z.0-9_\-]+/ }, except: [:new, :create, :index], path: "/" do
    member do
      put :transfer
      post :fork
      get :ci_build
      post "ci_build_single/:sha/:test_id" => "projects#ci_build_single", constraints: {sha: /\w+/, test_id: /.+/}, as: 'ci_build_single'
      get :ci
      put :ci_update
      post :unarchive
      get :autocomplete_sources
      get :runner_configs
    end

    scope module: :projects do
      resources :summary,   only: [:index], constraints: {id: /.+/}
      resources :test_issues,   only: [:index]
      resources :results,   only: [:index]
      resources :blob,      only: [:show, :destroy], constraints: {id: /.+/}
      resources :raw,       only: [:show], constraints: {id: /.+/}
      resources :tree,      only: [:show], constraints: {id: /.+/, format: /(html|js)/ }
      resources :edit_tree, only: [:show, :update], constraints: {id: /.+/}, path: 'edit'
      resources :new_tree,  only: [:show, :update], constraints: {id: /.+/}, path: 'new'
      resources :commit,    only: [:show], constraints: {id: /[[:alnum:]]{6,40}/}
      resources :commits,   only: [:show], constraints: {id: /(?:[^.]|\.(?!atom$))+/, format: /atom/}
      resources :blame,     only: [:show], constraints: {id: /.+/}

      match "/compare/:from...:to" => "compare#show", as: "compare", via: [:get, :post], constraints: {from: /.+/, to: /.+/}

        resources :snippets, constraints: {id: /\d+/} do
          member do
            get "raw"
          end
        end

      resources :wikis, only: [:show, :edit, :destroy, :create], constraints: {id: /[a-zA-Z.0-9_\-]+/} do
        collection do
          get :pages
          put ':id' => 'wikis#update'
          get :git_access
        end

        member do
          get "history"
        end
      end

      resource :wall, only: [:show], constraints: {id: /\d+/} do
        member do
          get 'notes'
        end
      end

      resource :repository, only: [:show] do
        member do
          get "stats"
          get "archive", constraints: { format: Gitlab::Regex.archive_formats_regex }
        end
      end

      resources :services, constraints: { id: /[^\/]+/ }, only: [:index, :edit, :update] do
        member do
          get :test
        end
      end

      resources :deploy_keys, constraints: {id: /\d+/} do
        member do
          put :enable
          put :disable
        end
      end

      resources :branches, only: [:index, :new, :create, :destroy], constraints: { id: Gitlab::Regex.git_reference_regex } do
        collection do
          get :recent, constraints: { id: Gitlab::Regex.git_reference_regex }
        end
      end

      resources :tags, only: [:index, :new, :create, :destroy], constraints: { id: Gitlab::Regex.git_reference_regex }
      resources :protected_branches, only: [:index, :create, :destroy], constraints: { id: Gitlab::Regex.git_reference_regex }

      resources :refs, only: [] do
        collection do
          get "switch"
        end

        member do
          # tree viewer logs
          get "logs_tree", constraints: { id: Gitlab::Regex.git_reference_regex }
          get "logs_tree/:path" => "refs#logs_tree",
            as: :logs_file,
            constraints: {
              id:   Gitlab::Regex.git_reference_regex,
              path: /.*/
            }
        end
      end

      resources :merge_requests, constraints: {id: /\d+/}, except: [:destroy] do
        member do
          get :diffs
          get :automerge
          get :automerge_check
          get :ci_status
        end

        collection do
          get :branch_from
          get :branch_to
          get :update_branches
        end
      end

      resources :hooks, only: [:index, :create, :destroy], constraints: {id: /\d+/} do
        member do
          get :test
        end
      end

      resources :team, controller: 'team_members', only: [:index]
      resources :milestones, except: [:destroy], constraints: {id: /\d+/}

      resources :labels, only: [:index] do
        collection do
          post :generate
        end
      end

      resources :issues, constraints: {id: /\d+/}, except: [:destroy] do
        collection do
          post  :bulk_update
        end
      end

      resources :team_members, except: [:index, :edit], constraints: { id: /[a-zA-Z.\/0-9_\-#%+]+/ } do
        collection do
          delete :leave

          # Used for import team
          # from another project
          get :import
          post :apply_import
        end
      end

      resources :notes, only: [:index, :create, :destroy, :update], constraints: {id: /\d+/} do
        member do
          delete :delete_attachment
        end

        collection do
          post :preview
        end
      end
    end
  end

  root to: "dashboard#show"
end

app/controllers/projects/application_controller.rb
class Projects::ApplicationController < ApplicationController
  before_filter :project
  before_filter :repository
  layout :determine_layout

  def authenticate_user!
    # Restrict access to Projects area only
    # for non-signed users
    if !current_user
      id = params[:project_id] || params[:id]
      @project = Project.find_with_namespace(id)

      return if @project && @project.public?
    end

    super
  end

  def determine_layout
    if current_user
      'projects'
    else
      'public_projects'
    end
  end

  def require_branch_head
    unless @repository.branch_names.include?(@ref)
      redirect_to project_tree_path(@project, @ref), notice: "This action is not allowed unless you are on top of a branch"
    end
  end

  def paginate(page_num, expanded, blocks)

    if(page_num.nil?)
      page_num = 1
    else
      page_num = page_num.to_d
    end

    sorted_blocks_unsliced =blocks.sort_by { |i| yield(i).feature }

    if(!(expanded.nil? || expanded.empty?))
      expanded_id = expanded.first

      index = sorted_blocks_unsliced.index { |i| i.id.to_s == expanded_id }

      if(!index.nil?)
        block_page_num = index.fdiv(PER_PAGE).truncate + 1

        if(block_page_num != page_num)
          return {:redirect => true, :addons => {:page => block_page_num}}
        end
      end
    end

    total_results = blocks.length

    offset = (page_num-1)*PER_PAGE
    limit = [ offset+PER_PAGE, total_results+1 ].min
    num_pages = total_results.fdiv(PER_PAGE).ceil
    num_pages = num_pages == 0 ? 1 : num_pages

    blocks_by_feature = {}

    sorted_blocks = sorted_blocks_unsliced[offset..limit-1]

    sorted_blocks.each { |i|
      feature = yield(i).feature

      if(blocks_by_feature[feature].nil?)
        blocks_by_feature[feature] = [i]
      else
        blocks_by_feature[feature] << i
      end
    }

    {:redirect => false, :num_pages => num_pages, :page_num => page_num, :blocks_by_feature => blocks_by_feature}
  end
end

app/controllers/projects/base_tree_controller.rb
class Projects::BaseTreeController < Projects::ApplicationController
  include ExtractsPath


  # before_filter :require_non_empty_project
end

app/controllers/projects/blame_controller.rb
# Controller for viewing a file's blame
class Projects::BlameController < Projects::ApplicationController
  include ExtractsPath

  # Authorize
  before_filter :require_non_empty_project

  def show
    @blob = @repository.blob_at(@commit.id, @path)
    @blame = Gitlab::Git::Blame.new(project.repository, @commit.id, @path)
  end
end

app/controllers/projects/commits_controller.rb
require "base64"

class Projects::CommitsController < Projects::ApplicationController
  include ExtractsPath

  # Authorize
  before_filter :require_non_empty_project

  def show
    @repo = @project.repository
    @limit, @offset = (params[:limit] || 40), (params[:offset] || 0)

    @commits = @repo.commits(@ref, @path, @limit, @offset)

    respond_to do |format|
      format.html # index.html.erb
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def remove_from_project_team_message(project, user)
    "You are going to remove #{user.name} from #{project.name} project team. Are you sure?"
  end

  def link_to_project project
    link_to project do
      title = content_tag(:span, project.name, class: 'projet-name')

      if project.namespace
        namespace = content_tag(:span, "#{project.namespace.human_name} / ", class: 'namespace-name')
        title = namespace + title
      end

      title
    end
  end

  def link_to_member(project, author, opts = {})
    default_opts = { avatar: true, name: true, size: 16 }
    opts = default_opts.merge(opts)

    return "(deleted)" unless author

    author_html =  ""

    # Build avatar image tag
    author_html << image_tag(avatar_icon(author.try(:email), opts[:size]), width: opts[:size], class: "avatar avatar-inline #{"s#{opts[:size]}" if opts[:size]}", alt:'') if opts[:avatar]

    # Build name span tag
    author_html << content_tag(:span, sanitize(author.name), class: 'author') if opts[:name]

    author_html = author_html.html_safe

    if opts[:name]
      link_to(author_html, user_path(author), class: "author_link").html_safe
    else
      link_to(author_html, user_path(author), class: "author_link has_tooltip", data: { :'original-title' => sanitize(author.name) } ).html_safe
    end
  end

  def project_title project
    if project.group
      content_tag :span do
        project.name
        # link_to(simple_sanitize(project.group.name), group_path(project.group)) + " / " + project.name
      end
    else
      owner = project.namespace.owner
      content_tag :span do
        project.name
        # link_to(simple_sanitize(owner.name), profile_path(owner)) + " / " + project.name
      end
    end
  end

  def project_link_to_user
    link_to(simple_sanitize(current_user.name), profile_path)
  end

  def remove_project_message(project)
    "You are going to remove #{project.name_with_namespace}.\n Removed project CANNOT be restored!\n Are you ABSOLUTELY sure?"
  end

  def project_nav_tabs
    @nav_tabs ||= get_project_nav_tabs(@project, current_user)
  end

  def project_nav_tab?(name)
    project_nav_tabs.include? name
  end

  def selected_label?(label_name)
    params[:label_name].to_s.split(',').include?(label_name)
  end

  def labels_filter_path(label_name)
    label_name =
      if selected_label?(label_name)
        params[:label_name].split(',').reject { |l| l == label_name }.join(',')
      elsif params[:label_name].present?
        "#{params[:label_name]},#{label_name}"
      else
        label_name
      end

    project_filter_path(label_name: label_name)
  end

  def label_filter_class(label_name)
    if selected_label?(label_name)
      'label-filter-item active'
    else
      'label-filter-item light'
    end
  end

  def project_filter_path(options={})
    exist_opts = {
      state: params[:state],
      scope: params[:scope],
      label_name: params[:label_name],
      milestone_id: params[:milestone_id],
      assignee_id: params[:assignee_id],
      sort: params[:sort],
    }

    options = exist_opts.merge(options)

    path = request.path
    path << "?#{options.to_param}"
    path
  end

  
  private

  def get_project_nav_tabs(project, current_user)
    nav_tabs = [:home]

    if !project.empty_repo? && can?(current_user, :download_code, project)
      nav_tabs << [:files, :commits, :network, :graphs]
    end

    if can?(current_user, :admin_project, project)
      nav_tabs << :settings
    end

    nav_tabs.flatten
  end

  def git_user_name
    if current_user
      current_user.name
    else
      "Your name"
    end
  end

  def git_user_email
    if current_user
      current_user.email
    else
      "your@email.com"
    end
  end

  def repository_size(project = nil)
    "#{(project || @project).repository.size} MB"
  rescue
    # In order to prevent 500 error
    # when application cannot allocate memory
    # to calculate repo size - just show 'Unknown'
    'unknown'
  end

  def project_head_title
    title = @project.name
    # title = @project.name_with_namespace

    title = if current_controller?(:tree)
              "#{@project.path}\/#{@path} at #{@ref} - " + title
            elsif current_controller?(:blob)
              "#{@project.path}\/#{@blob.path} at #{@ref} - " + title
            elsif current_controller?(:commits)
              "Commits at #{@ref} - " + title
            else
              title
            end

    title
  end

  def default_url_to_repo(project = nil)
    project = project || @project
    current_user ? project.url_to_repo : project.http_url_to_repo
  end

  def default_clone_protocol
    current_user ? "ssh" : "http"
  end

  def project_last_activity(project)
    if project.last_activity_at
      time_ago_with_tooltip(project.last_activity_at, 'bottom', 'last_activity_time_ago')
    else
      "Never"
    end
  end
end

app/views/projects/_builds.html.haml
.tab-content
  .tab-pane.active#builds
    .ui-box
      %ul.well-list.dash-list{class: ("unstyled" if with_status)}
        - @builds.each do |build|
          %li.project-row{class: (build.status == "SUCCESS" ? "success-row" : "alert-row" if with_status)}
            - if with_links
              %a.project{data: { url: build.url, status: build.status }, href: "#"}
                %span.str-truncated
                  %span.project-name.filter-title
                    - if build.type == Project::CiBuild::ALL
                      = "Build \##{build.number}"
                    - else
                      = "Test \##{build.number}"
            - else
              %span.str-truncated
                %span.project-name.filter-title
                  - if build.type == Project::CiBuild::ALL
                    = "Build \##{build.number}"
                  - else
                    = "Test \##{build.number}"

        - if @builds.empty?
          %li
            .nothing-here-block There are no builds

app/views/projects/_dropdown.html.haml
- if current_user
  .dropdown.pull-right
    %a.dropdown-toggle.btn.btn-new{href: '#', "data-toggle" => "dropdown"}
      %i.icon-reorder
    %ul.dropdown-menu
      - if @project.issues_enabled && can?(current_user, :write_issue, @project)
        %li
          = link_to url_for_new_issue, title: "New Issue" do
            New issue
      - if @project.merge_requests_enabled && can?(current_user, :write_merge_request, @project)
        %li
          = link_to new_project_merge_request_path(@project), title: "New Merge Request" do
            New merge request
      - if @project.snippets_enabled && can?(current_user, :write_snippet, @project)
        %li
          = link_to new_project_snippet_path(@project), title: "New Snippet" do
            New snippet
      - if can?(current_user, :admin_team_member, @project)
        %li
          = link_to new_project_team_member_path(@project), title: "New project member" do
            New project member
      - if can? current_user, :push_code, @project
        %li.divider
        %li
          = link_to new_project_branch_path(@project) do
            %i.icon-code-fork
            Git branch
        %li
          = link_to new_project_tag_path(@project) do
            %i.icon-tag
            Git tag

app/views/projects/_errors.html.haml
- if @project && @project.errors.any?
  .alert.alert-danger
    %button{ type: "button", class: "close", "data-dismiss" => "alert"}
    = @project.errors.full_messages.first

app/views/projects/_form_goals.html.haml
%h3.page-title
  Project Goals (%):
%fieldset
  .form-group
    =f.label :passed_goal, class: 'control-label' do
      Passed Features Goal
    .col-sm-10= f.text_field :passed_goal, placeholder: "100", class: "form-control"

  .form-group
    =f.label :automation_goal, class: 'control-label' do
      Automation Completion Goal
    .col-sm-10= f.text_field :automation_goal, placeholder: "90", class: "form-control"

app/views/projects/_form_jenkins.html.haml
%h3.page-title
  Continuous Integration Server Settings:
%fieldset
  .form-group
    =f.label :ci_url, class: 'control-label' do
      URL
    .col-sm-10= f.text_field :ci_url, placeholder: "http://jenkins.webcat.com/", class: "form-control"

  .form-group
    =f.label :ci_username, class: 'control-label' do
      Username
    .col-sm-10= f.text_field :ci_username, placeholder: "webcat", class: "form-control"

  .form-group
    =f.label :ci_password, class: 'control-label' do
      Password
    .col-sm-10= f.password_field :ci_password, class: "form-control"

  .form-group
    =f.label :ci_job_name, class: 'control-label' do
      Job name
    .col-sm-10= f.text_field :ci_job_name, placeholder: "awesome_job", class: "form-control"

  - if(with_schedule)
    .form-group
      =f.label :ci_job_name, class: 'control-label' do
        CI Job schedule
        %span.light (optional)
      .col-sm-10= f.text_area :ci_schedule, class: "form-control", rows: 3, maxlength: 250, disabled: (@project.nil? || !@project.has_ci_settings?)

  - unless @project.path.nil?
    %a{ href: "#{runner_configs_project_path(@project)}", id: "jenkins-configs", class: "btn btn-save pull-right" }
      Get CI configurations

    :javascript
      var getConfigs = document.getElementById("jenkins-configs");
      getConfigs.href += "?host=" + window.location.origin;

app/views/projects/_form_main.html.haml
%h3.page-title
  Project settings:

%fieldset
  .form-group.project_name_holder
    = f.label :name, class: 'control-label' do
      Project name
    .col-sm-10
      = f.text_field :name, placeholder: "Example Project", class: "form-control", required: true

  .form-group.project_name_holder
    = f.label :git_url, class: 'control-label' do
      Git URL
    .col-sm-10
      = f.text_field :git_url, placeholder: "https://github.com/webcat/webcat.git", class: "form-control", required: true, disabled: !is_creation

  .form-group
    = f.label :description, class: 'control-label' do
      Project description
      %span.light (optional)
    .col-sm-10
      = f.text_area :description, placeholder: "Awesome project", class: "form-control", rows: 3, maxlength: 250

  - if @repository && @repository.exists? && @repository.branch_names.any?
    .form-group
      = f.label :default_branch, "Default Branch", class: 'control-label'
      .col-sm-10= f.select(:default_branch, @repository.branch_names, {}, {class: 'select2 select-wide'})

  .form-group.project_name_holder
    = f.label :test_path, class: 'control-label' do
      Tests root path
    .col-sm-10
      = f.text_field :test_path, placeholder: 'src/test/resources/', class: "form-control", required: true

app/views/projects/_home_panel.html.haml
- empty_repo = @project.repo_exists? || @project.empty_repo?
.project-home-panel{:class => ("empty-project" if empty_repo)}
  .row
    .col-sm-10
      %h4.project-home-title
        = @project.name_with_namespace

  .project-home-extra.row
    .col-md-8
      .project-home-desc
        - if @project.description.present?
          = @project.description
        
    - unless empty_repo
      .col-md-4
        .project-home-links
          %span.light.prepend-left-20
            = pluralize(@repository.round_commit_count, 'commit')
          %span.light.prepend-left-20
            = pluralize(@repository.branch_names.count, 'branch')
          %span.light.prepend-left-20
            = pluralize(@repository.tag_names.count, 'tag')
          %span.light.prepend-left-20
            = repository_size

app/views/projects/_settings_nav.html.haml
%ul.nav.nav-pills.nav-stacked.nav-stacked-menu.append-bottom-20.project-settings-nav
  = nav_link(path: 'projects#edit') do
    = link_to edit_project_path(@project), class: "stat-tab tab " do
      %i.icon-edit
      Project
  = nav_link(controller: [:team_members, :teams]) do
    = link_to project_team_index_path(@project), class: "team-tab tab" do
      %i.icon-group
      Members

app/views/projects/ci.html.haml
= render "home_panel"
= render "errors"

- unless @project.has_ci_settings? && @valid_ci_settings
  .bs-callout.bs-callout-info
    %h4
      CI not configured
    %p
      Please create a job in your Jenkins server with the
      %a{href: "http://www.masterthought.net/section/cucumber-reporting", style: "color:#333;", target: "_blank" } Cucumber Reporting
      plugin enabled and configure your Jenkins Server in the Project Settings area.
- else
  .col-md-10
    .form-holder
      = form_for @project, url: ci_build_project_path(@project), method: :post do |f|
        %h3.page-title
          Run now:
        .well{style: "max-width:400px; margin: 0 auto 10px;"}
          = f.submit "Run now", class: "btn btn-primary btn-lg btn-block", disabled: !@project.has_ci_settings?

    %hr
    .form-holder
      = form_for @project, url: ci_update_project_path(@project), method: :put do |f|
        %h3.page-title
          Run Periodically:

        %fieldset
          .form-group
            = f.label :ci_schedule, class: "control-label" do
              Schedule for automatic runs
            .col-sm-10{style: "margin-bottom:20px"}
              = f.text_area :ci_schedule, class: "form-control", rows: 3, maxlength: 250, disabled: !@project.has_ci_settings?
            %span.light
              %pre.code
                = preserve do
                  :escaped
                    This field follows the syntax of cron (with minor differences). Specifically, each line consists of 5 fields separated by TAB or whitespace:
                    MINUTE HOUR DOM MONTH DOW
                    MINUTE  Minutes within the hour (0–59)
                    HOUR  The hour of the day (0–23)
                    DOM The day of the month (1–31)
                    MONTH The month (1–12)
                    DOW The day of the week (0–7) where 0 and 7 are Sunday.
                    To specify multiple values for one field, the following operators are available. In the order of precedence,

                    * specifies all valid values
                    M-N specifies a range of values
                    M-N/X or */X steps by intervals of X through the specified range or whole valid range
                    A,B,...,Z enumerates multiple values
                    To allow periodically scheduled tasks to produce even load on the system, the symbol H (for “hash”) should be used wherever possible. For example, using 0 0 * * * for a dozen daily jobs will cause a large spike at midnight. In contrast, using H H * * * would still execute each job once a day, but not all at the same time, better using limited resources.

                    The H symbol can be used with a range. For example, H H(0-7) * * * means some time between 12:00 AM (midnight) to 7:59 AM. You can also use step intervals with H, with or without ranges.

                    The H symbol can be thought of as a random value over a range, but it actually is a hash of the job name, not a random function, so that the value remains stable for any given project.

                    Empty lines and lines that start with # will be ignored as comments.

                    In addition, @yearly, @annually, @monthly, @weekly, @daily, @midnight, and @hourly are supported as convenient aliases. These use the hash system for automatic balancing. For example, @hourly is the same as H * * * * and could mean at any time during the hour. @midnight actually means some time between 12:00 AM and 2:59 AM.

                    Examples:

                    # every fifteen minutes (perhaps at :07, :22, :37, :52)
                    H/15 * * * *
                    # every ten minutes in the first half of every hour (three times, perhaps at :04, :14, :24)
                    H(0-29)/10 * * * *
                    # once every two hours every weekday (perhaps at 10:38 AM, 12:38 PM, 2:38 PM, 4:38 PM)
                    H 9-16/2 * * 1-5
                    # once a day on the 1st and 15th of every month except December
                    H H 1,15 1-11 *

        .form-actions
          = f.submit "Save", class: "btn btn-save", disabled: !@project.has_ci_settings?

  .side.col-md-2.hidden-sm.hidden-xs
    = render 'builds', with_links: false, with_status: true

app/views/projects/create.js.haml
- if @project.saved?
  :plain
    location.href = "#{project_path(@project)}";
- else
  :plain
    $(".project-edit-errors").html("#{escape_javascript(render('errors'))}");
    $('.project-submit').enable();
    $('.save-project-loader').hide();
    $('.project-edit-container').show();

app/views/projects/edit.html.haml
.row
  .col-md-2
    = render "settings_nav"

  .col-md-10
    = render("form", is_creation: false)

app/views/projects/empty.html.haml
= render "home_panel"

%h4
  Awesome reports stuff

app/views/projects/update.js.haml
- if @project.valid?
  :plain
    location.href = "#{edit_project_path(@project)}";
- else
  :plain
    $(".project-edit-errors").html("#{escape_javascript(render('errors'))}");
    $('.save-project-loader').hide();
    $('.project-edit-container').show();
    $('.project-edit-content .btn-save').enableButton();